[package]
name = "oxia"
version = "0.0.1"
authors = ["Michael Goulet <michael@errs.io>"]
edition = "2018"
build = "build.rs"
exclude = ["test/*"]

[build-dependencies]
lalrpop = "0.19.5"

[dependencies]
codespan-reporting = "0.11.1"
codespan-derive = { git = "https://github.com/compiler-errors/codespan-derive" }
structopt = "0.3.21"
camino = "1.0.4"
lalrpop-util = "0.19.5"
regex = "1"
simple_logger = "1.11.0"
log = "0.4.14"