[package]
name = "camp_files"
version = "0.1.0"
edition = "2018"

[dependencies]
camino = "1.0.5"
camp_util = { path = "../camp_util" }
codespan-derive = "0.1.1"
codespan-reporting = "0.11.1"
log = "0.4.14"
maplit = "1.0.2"
salsa = "0.16.1"
